### ISSUE TITLE
Calculate the overall time in GC [Parallel GC] for uploaded file

### ISSUE THREAD

**Issue by alex-dukhno** [CodeInten/jvm-log-analyzer#10]
Unfortunately, I don't have a Serial GC log file that is the simplest one I suppose. However, I have parallel GC one.  I attached to the issue.
[parallel-gc-debug.txt](https://github.com/CodeInten/jvm-log-analyzer/files/1117203/parallel-gc-debug.txt)

Let try calculate the overall time of that application was in GC phase. You need to find and parse lines that similar to the following one:
```txt
[0.220s][info ][gc,cpu               ] GC(0) User=0.11s Sys=0.00s Real=0.00s
```

**Comment by Dmitry404** [comment]
For a reference http://openjdk.java.net/jeps/158
