### ISSUE TITLE
Close Master and configure merge bot

### ISSUE THREAD

**Issue by alex-dukhno** [CodeInten/jvm-log-analyzer#5]
Should we make master branch read-only and configure a merge bot that automatically runs CI and only then perform PR merge? (i.e. [bors](https://github.com/bors-ng/bors-ng)) @Dmitry404 what do you think?

**Comment by Dmitry404** [comment]
I see not much sense in it. Same about read-only master. Perhaps to set a non-master branch as default would be good enough.

**Comment by alex-dukhno** [comment]
Closing as an unnecessary complication to the build process
